server.port: 7003
server.error.include-message: always

logging:
  level:
    root: INFO
    com.dvc: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG

spring.data.mongodb:
  host: localhost
  port: 27017
  database: recommendation-db

---
spring.profiles: docker

server.port: 8080

spring.data.mongodb.host: mongodb